spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/club27local
    username: testUser
    password: 1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      enabled:

users:
  listing:
    pageSize: 12
server:
  error:
    include-message: always